name: ðŸ”Ž Recon workflow

on:
    # schedule:
    #    - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
  recon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Amass - Enumeration
        uses: afonso/amass-action@main
        with:
          domains: ${{ vars.TARGET_DOMAIN }}
          brute: true
          output: hosts.txt
          
      - name: Prepare - Amass
        run: |
          awk -F ' --> ' '{
          gsub(/\([^)]+\)/, "", $1);
          gsub(/^[ \t]+|[ \t]+$/, "", $1);
          if ($1 !~ /\//) print $1;
          gsub(/\([^)]+\)/, "", $NF);
          gsub(/^[ \t]+|[ \t]+$/, "", $NF);
          if ($NF !~ /\//) print $NF;
          }' hosts.txt | sort -u > hosts_filtered.txt
      
      - name: Debug - Amass
        run: |
          cat hosts_filtered.txt
          
      - name: Naabu - Port Scannner
        uses: projectdiscovery/naabu-action@main
        with:
            list: hosts_filtered.txt
            output: urls.txt
      
      - name: Debug - Naabu
        run: |
          cat urls.txt
          
      - name: Nuclei - DAST Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: urls.txt
          output: nuclei.txt
    
      - name: Debug - Nuclei
        run: |
          cat nuclei.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hosts_filtered.txt
          path: |
            hosts_filtered.txt
            urls.txt
            nuclei.txt
